#!/bin/sh +x
# Create a temp file
TMPFILE=`mktemp` || exit 1
# Specify as an Org file for Emacs
echo "-*- mode: org -*-" >> $TMPFILE
# Write the staged version of init.org
git show :init.org >> $TMPFILE
# Tangle the temp file
TANGLED=`emacsclient -nw -s ~/.emacs.d/cache/server/server -e "(let ((enable-local-variables :safe)) (car (org-babel-tangle-file  \"$TMPFILE\")))"`
# Overwrite .emacs.d/init.el with the file that is based on the staged changes

mv -f "${TANGLED//\"}" init.el
# Stage the file
git add init.el
